[general]
import = [
    "themes/zenwritten_light.toml"
]

[window]
# startup_mode = "Fullscreen"
dimensions = { columns = 157, lines = 37 }
dynamic_padding = true

[font]
normal = { family = "Lilex", style = "Regular" }
# brewmaster: 17 | JAAM: 14
size = 14

[mouse]
hide_when_typing = true
